#!/bin/bash
# deploy-site-update.sh - Copy community data, regenerate site, commit+push if changed.
# Called by the Gemma4 research cron job after extraction.
# Pushes to main, which triggers the deploy-site.yml GitHub Actions workflow.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
WORKSPACE="${WORKSPACE:-/home/frank/.openclaw/workspace}"
CONFIGS_SRC="$WORKSPACE/knowledge/reddit/localllama/gemma4-hardware-configs.json"

echo "=== deploy-site-update: $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="
cd "$REPO_DIR"

# Ensure we are on main and up to date
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" != "main" ]; then
  echo "ERROR: not on main branch (on $BRANCH). Aborting."
  exit 1
fi
git pull --rebase origin main 2>/dev/null || true

# Step 1: Copy community data if source exists
mkdir -p site/data
if [ -f "$CONFIGS_SRC" ]; then
  cp "$CONFIGS_SRC" site/data/gemma4-hardware-configs.json
  echo "Copied gemma4-hardware-configs.json to site/data/"
else
  echo "WARN: $CONFIGS_SRC not found, skipping community data copy"
fi

# Step 2: Regenerate site
python3 scripts/site/generate-site.py
echo "Site regenerated."

# Step 3: Check if anything changed
if git diff --quiet site/ && git diff --quiet --cached site/; then
  echo "No site changes detected. Nothing to commit."
  exit 0
fi

# Step 4: Commit and push
git add site/
git commit -m "site: update with latest community hardware data

Auto-generated by deploy-site-update.sh from Gemma4 research cron."

git push origin main
echo "Pushed to main. GitHub Actions deploy-site.yml will publish."
echo "=== deploy-site-update: done ==="
