#!/bin/bash
# deploy-site-update.sh - Copy community data, regenerate site, commit+push if changed.
# Called by the Gemma4 research cron job after extraction.
# Pushes to main, which triggers the deploy-site.yml GitHub Actions workflow.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
WORKSPACE="${WORKSPACE:-/home/frank/.openclaw/workspace}"
CONFIGS_SRC="$WORKSPACE/knowledge/reddit/localllama/gemma4-hardware-configs.json"

echo "=== deploy-site-update: $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="
cd "$REPO_DIR"

# Ensure we are on main and up to date
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" != "main" ]; then
  echo "ERROR: not on main branch (on $BRANCH). Aborting."
  exit 1
fi
git pull --rebase origin main 2>/dev/null || true

# Step 1: Copy community data if source exists.
# Raw Reddit excerpts routinely contain typographic dashes (em/en/figure dash,
# minus sign). Those violate the deliverable style rule, so sanitize them to a
# plain ASCII hyphen during the copy. The sanitizer runs on the DECODED JSON, not
# on the file text: the extractor writes with ensure_ascii=True, so the dashes sit
# on disk as \uXXXX escapes that a text-level translate() cannot see. See
# scripts/site/copy-community-data.py for the full account.
mkdir -p site/data
if [ -f "$CONFIGS_SRC" ]; then
  python3 "$SCRIPT_DIR/copy-community-data.py" \
    "$CONFIGS_SRC" site/data/gemma4-hardware-configs.json
  # Format here rather than leaving it to the pre-commit hook. The copy writes the
  # extractor's one-row-per-line shape and the committed file is the oxfmt-collapsed
  # form of it, so without this the working tree shows a five-thousand-line reflow
  # between the copy and the commit, which is exactly what buried the real change in
  # earlier cycles. oxfmt is already a hard dependency of this script: the commit
  # below runs the pre-commit hook, which invokes it.
  if [ -x node_modules/oxfmt/bin/oxfmt ]; then
    node_modules/oxfmt/bin/oxfmt --write site/data/gemma4-hardware-configs.json >/dev/null
  else
    echo "WARN: node_modules/oxfmt not found, leaving site/data JSON unformatted"
  fi
  echo "Copied + dash-sanitized gemma4-hardware-configs.json to site/data/"
else
  echo "WARN: $CONFIGS_SRC not found, skipping community data copy"
fi

# Step 2: Regenerate site
WORKSPACE="$WORKSPACE" python3 scripts/site/generate-site.py
echo "Site regenerated."

# Step 2b: Run quality checks (fail early if raw Markdown or broken cards detected)
bash scripts/site/check-site-quality.sh
echo "Site quality checks passed."

# Step 3: Check if anything changed
if git diff --quiet site/ && git diff --quiet --cached site/; then
  echo "No site changes detected. Nothing to commit."
  exit 0
fi

# Step 4: Commit and push
git add site/
git commit -m "site: update with latest community hardware data

Auto-generated by deploy-site-update.sh from Gemma4 research cron."

git push origin main
echo "Pushed to main. GitHub Actions deploy-site.yml will publish."
echo "=== deploy-site-update: done ==="
