#!/bin/bash
# deploy-site-update.sh - Copy community data, regenerate site, commit+push if changed.
# Called by the Gemma4 research cron job after extraction.
# Pushes to main, which triggers the deploy-site.yml GitHub Actions workflow.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
WORKSPACE="${WORKSPACE:-/home/frank/.openclaw/workspace}"
CONFIGS_SRC="$WORKSPACE/knowledge/reddit/localllama/gemma4-hardware-configs.json"

echo "=== deploy-site-update: $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="
cd "$REPO_DIR"

# Ensure we are on main and up to date
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" != "main" ]; then
  echo "ERROR: not on main branch (on $BRANCH). Aborting."
  exit 1
fi
git pull --rebase origin main 2>/dev/null || true

# Step 1: Copy community data if source exists.
# Raw Reddit excerpts routinely contain typographic dashes (em/en/figure dash,
# minus sign). Those violate the deliverable style rule and trip the
# no-typographic-dashes gate, so sanitize them to a plain ASCII hyphen during the
# copy. This is a byte-level replacement of the dash characters only: all other
# JSON formatting is preserved verbatim to keep the committed diff minimal.
mkdir -p site/data
if [ -f "$CONFIGS_SRC" ]; then
  CONFIGS_SRC="$CONFIGS_SRC" python3 - <<'PY'
import os
src = os.environ["CONFIGS_SRC"]
dst = "site/data/gemma4-hardware-configs.json"
# Typographic dash code points -> ASCII hyphen. Listed numerically (not as literal
# characters) so this script itself stays free of typographic dashes.
codepoints = (0x2010, 0x2011, 0x2012, 0x2013, 0x2014,
              0x2015, 0x2043, 0x2E3A, 0x2E3B, 0x2212)
table = {cp: "-" for cp in codepoints}
with open(src, encoding="utf-8") as f:
    data = f.read()
with open(dst, "w", encoding="utf-8") as f:
    f.write(data.translate(table))
PY
  echo "Copied + dash-sanitized gemma4-hardware-configs.json to site/data/"
else
  echo "WARN: $CONFIGS_SRC not found, skipping community data copy"
fi

# Step 2: Regenerate site
WORKSPACE="$WORKSPACE" python3 scripts/site/generate-site.py
echo "Site regenerated."

# Step 2b: Run quality checks (fail early if raw Markdown or broken cards detected)
bash scripts/site/check-site-quality.sh
echo "Site quality checks passed."

# Step 3: Check if anything changed
if git diff --quiet site/ && git diff --quiet --cached site/; then
  echo "No site changes detected. Nothing to commit."
  exit 0
fi

# Step 4: Commit and push
git add site/
git commit -m "site: update with latest community hardware data

Auto-generated by deploy-site-update.sh from Gemma4 research cron."

git push origin main
echo "Pushed to main. GitHub Actions deploy-site.yml will publish."
echo "=== deploy-site-update: done ==="
